### PR TITLE
Allow usage with Monolog 2

### LINKED ISSUE #3: Update monolog dependencies
Hello, Our project is fixed to Monolog 2.3.* currently. Looking through the code, I see little reason to think your processors wouldn't work above **monolog/monolog ^1.17**

Do you mind if I update the composer.json dependency and make a pull request?

### PR DESCRIPTION
**Pull request by rimas-kudelis**
Additionally:
- the processors now implement ProcessorInterface
- PHPUnit dependency updated to ^8.5 (^9.5 requires additional changes)
- Travis configured to build with currently supported PHP versions
- composer.lock has been removed

Fixes #3

### CODE REVIEW

**Comment by rimas-kudelis** [comment]
@andriesss would you mind reviewing this and tagging a new release if all is good?

**Comment by andriesss** [comment]
Thanks @rimas-kudelis! Why did you remove the `composer.lock` file?

**Comment by rimas-kudelis** [comment]
@andriesss this is a library, what's the point of locking its dependencies? That lock will be ignored when installing this package as a dependency anyway.

Furthermore, should you decide to configure testing dependencies as a matrix (e.g. not just PHP 7.4, 8.0 and 8.1, but instead combinations of these PHP versions with Monolog 1 and 2), `composer.lock` would probably just get in the way of that.

**Comment by rimas-kudelis** [comment]
Also notably, Monolog 3 has been released recently. I haven't added it as a supported dependency, because it uses `LogRecord` objects instead of arrays. Although it seems that that class implements ArrayAccess for BC, so it might just work with extra typehints.

**Comment by rimas-kudelis** [comment]
@andriesss, Packagist says that "This package is not [auto-updated](https://packagist.org/about#how-to-update-packages).". Could you ping Packagist as well (or just configure automatic updating)? Thanks!

**Comment by andriesss** [comment]
@rimas-kudelis done.

**Comment by rimas-kudelis** [comment]
@andriesss thanks! Also, Travis-CI no longer builds anything on travis-ci.org, so the badge in the README is now misleading.

**Comment by andriesss** [comment]
@rimas-kudelis could you give me some pointers on how to fix that? It's been a while since I've last used Travis.

**Comment by rimas-kudelis** [comment]
@andriesss sure, see #5 :)

**Pull request merged**
